spring.application.name=devarchive
server.port=${SERVER_PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9yRGV2QXJjaGl2ZUFwcGxpY2F0aW9uVGhhdElzQXRMZWFzdDUxMkJpdHNMb25n
jwt.expiration=86400000
